### ISSUE TITLE
sliverappbar展开到全屏的时候页面怎么控制?

### ISSUE THREAD

**Issue by ShuWangSam** [CyJaySong/flutter_meituan_shop#2]
新手在学flutter, 看到了知乎上的教程,
但是在sliverappbar收缩和展开的位置, 我flexiableSpaceBar里面的内容不是放大就是缩小, 或者位置发生了改变.
能提供一下demo里面的思路么, 我做了一天实在没做出来

**Comment by CyJaySong** [comment]
你想要实现什么效果呢

**Comment by ShuWangSam** [comment]
就是demo里面那种向下滑动的时候，餐馆名字位置不变，flexiableSpaceBar全屏后内容会改变

**Comment by CyJaySong** [comment]
监听滑动，在flexiableSpaceBar里面放一个组件，把滑动事件传给组件，让组件判断，什么时候，应该显示什么样的内容
