### ISSUE TITLE
有办法在现在的 listview 里加上下拉刷新吗

### ISSUE THREAD

**Issue by bayun2** [CyJaySong/flutter_meituan_shop#3]
现在 CustomScrollView 的 physics 被设置成了 ClampingScrollPhysics ，无法触发 RefreshIndicator。但是如果移除了 ClampingScrollPhysics 联动的滚动又会出问题。
将 CustomScrollView 的 physics 改回默认的 AlwaysScrollableScrollPhysics 后，问题：

1. 内部滚动列表就无法正常回弹回顶部
2. 内部滚动列表滚动 onPointerUp 时，每次都出现了向下回弹的效果

解决：
问题1，可以修改 onPointerUp ，在 _pagePixels < 0.0 时，通过手动将 _pageScrollPosition 滚到顶部，来解决了无法正常回弹顶部的问题
问题2 ，暂时没有想到解决方案

**Comment by CyJaySong** [comment]
挺复杂的，一时半会儿没思路，最近搞后端
