### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by cjl84914** [CyJaySong/flutter_meituan_shop#4]
flutter 2.0.0 报错
`Null check operator used on a null value`

**Comment by CyJaySong** [comment]
null_safety 分支？？？

**Comment by cjl84914** [comment]
@CyJaySong  thank you

**Comment by KuuBee** [comment]
请问解决了吗,还是说我要切换到1.0的版本.

**Comment by CyJaySong** [comment]
> 请问解决了吗,还是说我要切换到1.0的版本.

flutter2 请参考 null_safety 分支
