### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by 309791679** [CyJaySong/flutter_meituan_shop#5]
能用缺报错，controller: _pageScrollController,使用这个就会报错 Null check operator used on a null value
去除 
The following assertion was thrown while dispatching a pointer event:
ScrollController not attached to any scroll views.
'package:untitled2/shop/shop_scroll_controller.dart':
Failed assertion: line 67 pos 12: '_positions.isNotEmpty'

**Comment by 309791679** [comment]
页面可以正常滑动，但是会报错，能力有限不知道怎么解决

**Comment by CyJaySong** [comment]
见[null_safety分支](https://github.com/CyJaySong/flutter_meituan_shop/tree/null_safety)
